In [54]:
# --------- Excersice 1 - Duplicates
import pandas as pd
train = pd.read_csv('train.csv')
train_no_duplicates = train.drop_duplicates()
if len(train_no_duplicates) < len(train):
    print(f"There were {len(train) - len(train_no_duplicates)} duplicate lines that were removed from the data")
else:
    print(f"There were no duplicated to remove")

if True in train.duplicated():
    print(f"duplicates")
else:
    print(f"no duplicates")

There were no duplicated to remove
no duplicates

In [48]:
# -------------- Excersice 2 - Missing values
from sklearn.impute import SimpleImputer

# remove lines with no value at Embarked

train["Cabin"] = train["Cabin"].fillna("No Cabin")
train.dropna(subset=['Embarked'], inplace=True)

# replace lines with no Age value with the mean Age

imputer = SimpleImputer(strategy="mean")
train["Age"] = imputer.fit_transform(train[["Age"]])

In [49]:
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,No Cabin,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,No Cabin,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,No Cabin,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,No Cabin,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.642093,1,2,W./C. 6607,23.4500,No Cabin,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,No Cabin,Q

In [50]:
# ---------- Exercise 3 

train["Family_Size"] = 1 + train["SibSp"] + train["Parch"]

train["Title"] = train["Name"].str.extract(r",\s*([^\.]+)\.")

train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,No Cabin,S,2,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,2,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,No Cabin,S,1,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,2,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,No Cabin,S,1,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,No Cabin,S,1,Rev
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,1,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.642093,1,2,W./C. 6607,23.4500,No Cabin,S,4,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,1,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,No Cabin,Q,1,Mr

In [51]:
# ---------- Exercise 4

# Identify and handle outliers in 'Fare' column
P2 = train['Fare'].quantile(0.02)
P98 = train['Fare'].quantile(0.98)
IPR = P98 - P2
lower_bound = P2 - 1.5 * IPR
upper_bound = P98 + 1.5 * IPR
train = train[(train['Fare'] >= lower_bound) & (train['Fare'] <= upper_bound)]

len(train)

# Identify and handle outliers in 'Age' column
P2 = train['Age'].quantile(0.02)
P98 = train['Age'].quantile(0.98)
IPR = P98 - P2
lower_bound = P2 - 1.5 * IPR
upper_bound = P98 + 1.5 * IPR
train = train[(train['Age'] >= lower_bound) & (train['Age'] <= upper_bound)]

len(train)

889

In [52]:
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,No Cabin,S,2,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,2,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,No Cabin,S,1,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,2,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,No Cabin,S,1,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,No Cabin,S,1,Rev
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,1,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.642093,1,2,W./C. 6607,23.4500,No Cabin,S,4,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,1,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,No Cabin,Q,1,Mr